// Code generated by mockery v1.0.0. DO NOT EDIT.

// @generated

package get

import context "context"
import data "github.com/gy-kim/golang-daily-practice/2019/08-Aug/21-31/26-31/hands-on-dependency-injection-in-go/ch09/acme/internal/modules/data"
import mock "github.com/stretchr/testify/mock"

// mockMyLoader is an autogenerated mock type for the myLoader type
type mockMyLoader struct {
	mock.Mock
}

// Load provides a mock function with given fields: ctx, ID
func (_m *mockMyLoader) Load(ctx context.Context, ID int) (*data.Person, error) {
	ret := _m.Called(ctx, ID)

	var r0 *data.Person
	if rf, ok := ret.Get(0).(func(context.Context, int) *data.Person); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.Person)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
