// Code generated by mockery v1.0.0. DO NOT EDIT.

// @generated

package rest

import data "github.com/gy-kim/golang-daily-practice/2019/08-Aug/21-31/26-31/hands-on-dependency-injection-in-go/ch09/acme/internal/modules/data"
import mock "github.com/stretchr/testify/mock"

// MockListModel is an autogenerated mock type for the ListModel type
type MockListModel struct {
	mock.Mock
}

// Do provides a mock function with given fields:
func (_m *MockListModel) Do() ([]*data.Person, error) {
	ret := _m.Called()

	var r0 []*data.Person
	if rf, ok := ret.Get(0).(func() []*data.Person); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*data.Person)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
